version: '3.8'

services:
  postgres:
    image: postgres
    container_name: db_molecules_fastapi_test
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
    ports:
      - 54321:5432
