
version: '3.8'

services:

  redis:
    image: "redis/redis-stack"
    container_name: redis_dev
    ports:
      - ${REDIS_PORT}:6379
    env_file:
      - .env_dev
    networks:
      - test_network


  postgres:
    image: postgres
    container_name: db_molecules_fastapi_dev
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    env_file:
      - .env_dev
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    networks:
        - dev_network


networks:
    dev_network:

volumes:
    postgres_data_dev:
