version: '3.8'

services:
  postgres:
    image: postgres
    container_name: db_molecules_fastapi
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
        - db_data:/var/lib/postgresql/data

  redis:
    image: redis/redis-stack
    ports:
      - ${REDIS_PORT}:6379

  celery_worker:
    build: .
    environment:
        ENVIRONMENT: PROD
    entrypoint: celery -A src.celery_worker worker --loglevel=info
    depends_on:
      - redis
      - postgres

  flower:
    build: .
    environment:
        ENVIRONMENT: PROD
    entrypoint: celery -A src.celery_worker flower --port=5555
    ports:
      - "5555:5555"
    depends_on:
      - celery_worker

  web1:
    build: .
    image: app
    environment:
      SERVER_ID: SERVER-1
      ENVIRONMENT: PROD
    depends_on:
      - postgres
      - redis
    entrypoint: ["/bin/sh", "-c", "alembic upgrade head && fastapi run src/main.py"]

  web2:
    image: app
    environment:
      SERVER_ID: SERVER-2
      ENVIRONMENT: PROD
    depends_on:
      - web1


# The reason why I did not use the build option for web2 is that It will result
# in the creation of a new image for web2, which is not really a problem(memory-wise layer architecture saves space),
# but I thought it would be better to use have just one image

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - web1
      - web2


volumes:
    db_data:

