version: '3.8'

services:

  redis:
    image: "redis/redis-stack"
    container_name: redis_test
    ports:
      - ${REDIS_PORT}:6379
    env_file:
      - .env_test
    networks:
      - test_network

  postgres:
    image: postgres
    container_name: db_molecules_fastapi_test
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    env_file:
      - .env_test

    networks:
        - test_network

networks:
    test_network:

