name: Build Docker Image
on:
  push:
    branches:
      - main
      - develop/drugs_and_molecules
  pull_request:
    branches:
      - main
      - develop/drugs_and_molecules

jobs:
    build:
      name: push docker image to docker hub
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: login to docker hub
          id: docker-hub
          env:
            username: gaiozi
            password: ${{secrets.DOCKERHUB_PASSWORD}}
          run: |
            docker login -u $username -p $password
        - name: build the docker image
          id: build-docker-image
          run: |
            ls -la 
            docker build -t gaiozi/molecules_api .
        - name: push the docker image
          id: push-docker-image
          run: docker push gaiozi/molecules_api:latest