name: linting

on:
  push:
    branches:
      - main
      - develop/drugs_and_molecules
      - feature/add_drugs
  pull_request:
    branches:
      - develop/drugs_and_molecules
      - feature/add_drugs
      - main


jobs:
  lint:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'


      - name: Install dependencies for linting
        run: |
          pip install flake8

      - name: Run flake8 linting
        run: |
          flake8 src
