name: Run Tests and Check Coverage
# This workflow is triggered on pushes to the develop branch and pull requests to the develop branch.
# It runs the tests and checks the coverage of the code.
# For some reason I had to use python 3.10 in dockerfile and here i will leave it is

on:
  push:
    branches:
      -main
  pull_request:
    branches:
      -develop/drugs_and_molecules,main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'


      - name: Install dependencies for linting
        run: |
          pip install flake8

      - name: Run flake8 linting
        run: |
          flake8 src

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'


      - name: Install dependencies for testing
        run: |
          pip install -r requirements.txt

      - name: Run tests with coverage
        run: |
          pytest --cov=src --cov-fail-under=95
