name: Run Tests and Check Coverage
# This tests require a postgres database for running.
# Let's say, Integration tests should cover at least 95% of the codebase
# I added the --cov-fail-under=95 option

on:
  push:
    branches:
      - main
      - develop/drugs_and_molecules
      - feature/add_drugs
  pull_request:
    branches:
      - develop/drugs_and_molecules
      - feature/add_drugs
      - main


jobs:

  integration-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: test_db
        ports:
          - 54321:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'


      - name: Install dependencies for testing
        run: |
          pip install -r requirements.txt

      - name: Run tests with coverage
        run: |
          pytest --cov=src --cov-fail-under=95
        env:
          TEST_DB_URL: postgresql://test_user:test_password@localhost:54321/test_db

