name: Run Tests and Check Coverage
# This workflow is triggered on pushes to the main branch and pull requests to the main branch.
# It runs the tests and checks the coverage of the code.
# For some reason I had to use python 3.10 in dockerfile and here i will leave it is

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Common setup
        uses: ./.github/workflows/common-setup.yml

      - name: Install dependencies for linting
        run: |
          pip install flake8

      - name: Run flake8 linting
        run: |
          flake8 src

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Common setup
        uses: ./.github/workflows/common-setup.yml

      - name: Install dependencies for testing
        run: |
          pip install -r requirements.txt

      - name: Run tests with coverage
        run: |
          pytest --cov=src --cov-fail-under=95
